enableGlobalCache: true

enableTelemetry: false

logFilters:
  # Missing Peer Dependency - only the package author can fix
  - code: YN0002
    level: discard
  # telling us what it needs to build; verbose and distracts from errors
  - code: YN0007
    level: discard
  # logs each package download; so verbose that it slows down iterm2
  - code: YN0013
    level: discard
  # architecture/os is incompatible and package will be skipped; expected and not useful signal
  - code: YN0076
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.3.1.cjs
